# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SwiftLintDmeo' do

	pod 'SwiftLint'

  target 'SwiftLintDmeoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftLintDmeoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

